ticket page/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('',views.PostLV.as_view(),name='index'),
    
    # Example: /blog/post/ (same as /blog/)
    path('post/',views.PostLV.as_view(),name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/',views.PostAV.as_view(),name='post_archive'),
    
    # Example: /blog/archive/2022/
    path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
    
    # Example: /blog/archive/2022/sep/
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month_archive'),

    # Example: /blog/archive/2022/sep/16/
    path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(),name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),
    
    # tag cloud 페이지 추가
    path('tag/',views.TagCloudLV.as_view(),name='tag_cloud'),
    
    # tagged object list 추가
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/',views.SearchFormView.as_view(), name='search'),
    
    path('add/',views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

ticket page/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',views.HomeView.as_view(),name='home'),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
    path('musical/',include('musical.urls')),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register',views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done',views.UserCreateDoneTV.as_view(), name='register_done'),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ticket page/photo/urls.py
from django.urls import path
from photo import views



app_name = 'photo'

urlpatterns = [
    path('',views.AlbumLV.as_view(),name='index'),
    path('album',views.AlbumLV.as_view(),name='album_list'),
    
    path('album/<int:pk>/',views.AlbumDV.as_view(),name='album_detail'),
    path('photo/<int:pk>/',views.PhotoDV.as_view(), name='photo_detail'),
    
    path('album/add/', views.AlbumCV.as_view(), name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/',views.AlbumUV.as_view(),name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(),name='album_delete'),
    
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/',views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(),name='photo_delete'),
]

ticket page/photo/models.py
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name="OWNER",blank=True,null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))
        # path('??/'<int:id>', ViewName.as_view(), name='album_detail')

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name="OWNER",blank=True,null=True)


    class Meta:
        ordering = ('title',)
         
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

ticket page/photo/forms.py
from django.forms import inlineformset_factory
from .models import *

PhotoInlineFormSet = inlineformset_factory(Album,
                                           Photo,
                                           fields = ['image','title','description'],
                                           extra = 2
                                           )

ticket page/photo/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import Album, Photo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .forms import PhotoInlineFormSet
from mysite.views import OwnerOnlyMixin

# Create your views here.
class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

class AlbumCV(LoginRequiredMixin, CreateView):
    model=Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid() :
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'
    
    def get_queryset(self):
        return Album.objects.filter(owner = self.request.user)
    
class AlbumUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else :
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else :
            return self.render_to_response(self.get_context_data(form=form))

class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')
    
class PhotoCV(LoginRequiredMixin, CreateView):
    model=Photo
    fields = ('album', 'title','image','description')
    success_url = reverse_lazy('photo:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'
    
    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUV(OwnerOnlyMixin, UpdateView):
    model=Photo
    fields = ('album', 'title','image','description')
    success_url = reverse_lazy('photo:index')
    
class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

ticket page/photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Album Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
    <br>
    
    <form method="post">{% csrf_token %}
        <p>앨범 "{{ object }}"을/를 삭제하면, 그 안의 모든 사진들도 삭제됩니다. 동의하십니까?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/photo/templates/photo/album_detail.html
{% extends "base.html" %}

<!-- 제목 블록 start -->
{% block title %}
{% endblock %}

<!-- 스타일 블록 start -->
{% block extra-style %}
{% endblock %}

<!-- 콘텐츠 블록 start -->
{% block content %}
{% endblock %}

<!-- 스크립트 블록 start -->
{% block extra-script %}
{% endblock %}

ticket page/photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<h1>Album-Photo Create/Update - {{user}}</h1>
<p class="font-italic">PhotoInlineFormSet을 이용한 추가, 수정 폼 화면입니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
    {{ formerrors }}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
        {% endif %}
        {% csrf_token %}

        <h4>앨범을 추가하거나 수정하세요</h4>

        <fieldset class="card pt-3">

            <div class="form-group row">
                {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.description|add_class:"form-control" }}
                </div>
            </div>

        </fieldset>

        <br>

        <h4>사진을 추가하거나 수정하세요.</h4>

        <fieldset class="card pt-3">

            {{ formset.management_form }}
            {% for form in formset %}
            {{ form.id }}
            {# form.album #}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <hr>
            {% endfor %}

        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/photo/templates/photo/album_list.html
{% extends "base.html" %}

<!-- 제목 블록 start -->
{% block title %}
{% endblock %}

<!-- 스타일 블록 start -->
{% block extra-style %}
<style>
    .thumbnail {
        border: 3px #ccc;
    }

    .poster {
        width: 350px;
    }
    .ms5-l-tit {
        font-size: 26px;
        width: 1110px;
        color: #333;
        left: 54px;
        top: 52px;
        font-weight: bold;
        font-family: 'Noto Sans KR','NanumBarunGothic','맑은 고딕','Malgun Gothic',sans-serif;
    }
   .card-deck{
    width:830px;
   }
   .card-title{
    background: url(http://tkfile.yes24.com/imgNew/genre/ico-ms5-r-tit.png)no-repeat right center;
   }
   a{
    color:#716DF2;
  }
  a:hover{
    color:#46658C;
  }
</style>
{% endblock %}

<!-- 콘텐츠 블록 start -->
{% block content %}
<br>
<br>

    {% for object in object_list %}
        <h3>{{ object }}</h3>
        <h5>{{ object.description }}</h5><br>
<div class='row'>
        {% for photo in object.photo_set.all %}
            
                <div class="thumbnail col-4">
                    <img src="{{ photo.image.url }}" class="poster" alt="{{ photo }}">
                </div>
           
        {% endfor %} </div>
        <hr>
    {% endfor %}


<p class="ms5-l-tit">WEEKLY RANKING&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📌지역별 추천</p>
<div class="row">
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <a href="http://ticket.yes24.com/Special/43485">
          <li class="list-group-item">1. KEY CONCERT - G.O.A.T.(Greatest Of All Time) IN THE KEYLAND</li></a>
          <a href="https://tickets.interpark.com/goods/22011921">
          <li class="list-group-item">2. 2022 KIM HO JOONG CONCERT TOUR [ARISTRA]</li></a>
          <a href="https://tickets.interpark.com/goods/22011684">
          <li class="list-group-item">3. 2022 SOMEDAY PLEROMA</li></a>
          <a href="http://ticket.yes24.com/Perf/43607">
          <li class="list-group-item">4. [지정석] 2022 창원 K-POP WORLD FESTIVAL</li></a>
          <a href="http://ticket.yes24.com/Perf/43185?Gcode=009_303">
          <li class="list-group-item">5. 그랜드 민트 페스티벌 2022</li></a>
          <a href="https://tickets.interpark.com/goods/22013007">
          <li class="list-group-item">6. 거미 20주년 전국투어 콘서트〈BE ORIGIN〉-수원</li></a>
          <a href="https://tickets.interpark.com/goods/22011593">
          <li class="list-group-item">7. 2022 하이라이트 팬콘［하이라이트 운동회]</li></a>
          <a href="http://ticket.yes24.com/Special/43642">
          <li class="list-group-item">8. [울산] 2022년 ‘Dream 55’ 나훈아 콘서트</li></a>
          <a href="https://tickets.interpark.com/goods/22012364">
          <li class="list-group-item">9. 2022 폴킴 전국투어 콘서트〈STAR〉- 대구</li></a>
          <a href="http://ticket.yes24.com/Perf/43060">
          <li class="list-group-item">10. 서울숲재즈페스티벌 2022 - 공식 티켓</li></a>
          <a href="https://tickets.interpark.com/goods/22012294">
          <li class="list-group-item">11. 2022 안동 K-POP 콘서트</li></a>
          <a href="https://ticket.melon.com/performance/index.htm?prodId=207277">
          <li class="list-group-item">12. 2022 AWESOME MUSIC FESTIVAL</li></a>
        </ul>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <div class="card-deck">
        <div class="card">
          <a href="http://ticket.yes24.com/Perf/43397">
          <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220902/20220902-43397.jpg" class="card-img-top" alt="..."></a>
          <div class="card-body">
            <h5 class="card-title">[창원] 케이윌 콘서트</h5>
            <p class="card-text">총 150분<br><br>* 공연시간<br>10월 22일(토) 오후 6시<br>
                10월 23일(일) 오후 5시<br><br><br><br>* 티켓수령안내<br>현장수령 또는 등기우편
              </p>
            <p class="card-text"><small class="text-muted">2022.10.22 ~ 2022.10.23</small></p>
          </div>
        </div>
        <div class="card">
          <a href="http://ticket.yes24.com/Perf/43637">
          <img src="https://ticketimage.interpark.com/Play/image/large/22/22013099_p.gif" class="card-img-top" alt="..." style="height:342.53px"></a>
          <div class="card-body">
            <h5 class="card-title">[광주] 거미 콘서트</h5>
            <p class="card-text">총 120분<br><br>* 공연시간<br>12월 17일(토) 오후 6시 <br>12월 18일(일) 오후 4시<br><br><br><br>* 티켓수령안내<br>현장수령 또는 등기우편</p>
            <p class="card-text"><small class="text-muted">2022.12.17 ~2022.12.18</small></p>
          </div>
        </div>
        <div class="card">
          <a href="http://ticket.yes24.com/Perf/42784">
          <img src="http://tkfile.yes24.com/upload2/PerfBlog/202207/20220727/20220727-42784.jpg" class="card-img-top" alt="..."></a>
          <div class="card-body">
            <h5 class="card-title">[서울] 슬로우 라이프 슬로우 라이브</h5>
            <p class="card-text">총 540분(인터미션 0분)<br><br>* 공연시간<br>10월 8일 (토) ~ 10(월)<br>
                오후 1시 ~ 10시<br><br><br>* 티켓수령안내<br>현장수령</p>
            <p class="card-text"><small class="text-muted">2022.10.08 ~ 2022.10.10</small></p>
          </div>
        </div>
      </div>
</div>

{% endblock %}

<!-- 스크립트 블록 start -->
{% block extra-script %}
{% endblock %}

ticket page/photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Photo Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-info">
                <th>Album</th>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.album }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Photo Delete</h1>
    <br>
    
    <form method="post"> {% csrf_token %}
        <p>이미지 "{{ object }}"을/를 진심으로 삭제하는건가요?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

<!-- 제목 블록 start -->
{% block title %}
album_detail.html
{% endblock %}

<!-- 스타일 블록 start -->
{% block extra-style %}
{% endblock %}

<!-- 콘텐츠 블록 start -->
{% block content %}
{% endblock %}

<!-- 스크립트 블록 start -->
{% block extra-script %}
{% endblock %}

ticket page/photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<h1>Photo Create/Update - {{ user }}</h1>
<p class="font-italic">사진 업로드 또는 수정을 진행할 수 있습니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" class="card pt-3">
{% else %}
    <form method="post" class="card pt-3">
{% endif %}
        {% csrf_token %}

        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">
                    Add Album</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->