ticket page/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('',views.PostLV.as_view(),name='index'),
    
    # Example: /blog/post/ (same as /blog/)
    path('post/',views.PostLV.as_view(),name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/',views.PostAV.as_view(),name='post_archive'),
    
    # Example: /blog/archive/2022/
    path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
    
    # Example: /blog/archive/2022/sep/
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month_archive'),

    # Example: /blog/archive/2022/sep/16/
    path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(),name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),
    
    # tag cloud 페이지 추가
    path('tag/',views.TagCloudLV.as_view(),name='tag_cloud'),
    
    # tagged object list 추가
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/',views.SearchFormView.as_view(), name='search'),
    
    path('add/',views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

ticket page/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('',views.BookmarkLV.as_view(),name='index'),
    path('<int:pk>/',views.BookmarkDV.as_view(),name='detail'),
    
    path('add/',views.BookmarkCreateView.as_view(),name='add'),
    path('change/',views.BookmarkChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.BookmarkUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.BookmarkDeleteView.as_view(),name='delete'),
]

ticket page/musical/urls.py
from django.urls import path
from musical import views

app_name = 'musical'

urlpatterns = [
    path('',views.MusicalLV.as_view(),name='index'),
    path('<int:pk>/',views.MusicalDV.as_view(),name='detail'),
]

ticket page/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',views.HomeView.as_view(),name='home'),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
    path('musical/',include('musical.urls')),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register',views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done',views.UserCreateDoneTV.as_view(), name='register_done'),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ticket page/photo/urls.py
from django.urls import path
from photo import views



app_name = 'photo'

urlpatterns = [
    path('',views.AlbumLV.as_view(),name='index'),
    path('album',views.AlbumLV.as_view(),name='album_list'),
    
    path('album/<int:pk>/',views.AlbumDV.as_view(),name='album_detail'),
    path('photo/<int:pk>/',views.PhotoDV.as_view(), name='photo_detail'),
    
    path('album/add/', views.AlbumCV.as_view(), name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/',views.AlbumUV.as_view(),name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(),name='album_delete'),
    
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/',views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(),name='photo_delete'),
]

ticket page/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Ticket{% endblock %}
    </title>
    <!-- Bootstrap CSS only -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    {% block extra-style %}

    {% endblock %}
</head>

<body >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Ticket🎫</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn"> 
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'photo:index' %}">Concert</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'musical:index' %}">Musical</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Ticket Open</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">Review</a>
                </li>
                <!-- 로그인 상태일 때만 Add, Change, Dropdown 표시-->
                {% if user.is_active %} 
                    <li class="nav-item dropdown mx-1 btn">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'bookmark:add' %}">bookmark</a>
                            <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                            <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown mx-1 btn">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'bookmark:change' %}">bookmark</a>
                            <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                            <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown mx-1 btn">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Tip</a>
                        <div class="dropdown-menu">
                            <!-- user_name이 admin 일 때만 admin 표시-->
                            {% if user.get_username == "admin" %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                            <div class="dropdown-divider"></div>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'blog:post_archive'%}">Archive</a>
                            <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                        </div>
                    </li>
                {% endif %}
            </ul>

            <!-- 회원(로그인/로그아웃/회원가입/비밀번호 변경) Start -->
            <ul class="navbar-nav mx-5">
                <li class="nav-item dropdown mx-1 btn btn-dark">
                    {% if user.is_active %} <!-- 로그인된 상태라면 -->
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        로그인 / 회원가입
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>


    
    <div class="container" style="min-height:85vh;">
        {% block content %}
        {% endblock %}
    </div>
    <hr>
    <footer>
        <div class="container" >
            <div class="footer_logo">Ticket🎫</div>
            <div id="contact_info">
                <p>
                    <a class="text-decoration-none" href="tel:+821012345678"><i class="fa-solid fa-phone"></i>&emsp;010-1234-5678</a>
                    <br>
                    <a class="text-decoration-none" href="mailto:walwal2@gmail.com"><i class="fa-solid fa-envelope"></i>&emsp;walwal2@gmail.com</a>
                    <br>
                    <a class="text-decoration-none" href="https://www.instagram.com/interparkticket/" target="_blank"><i class="fa-brands fa-square-instagram"></i>&emsp;Who Am !</a>
                </p>
            </div>
            <p style="color:#646873">Copyright © <b>JY's</b> All rights reserved.</p>
        </div>
    </footer>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/600ceba5b1.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


    {% block extra-script %}
    {% endblock %}

</html>

ticket page/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ticket{% endblock%}

{% block extra-style %}
<style>
  .carousel-inner {
    height: 396.42px;
  }

  .card-open {
    width: 540px;
  }

  .card-open1 {
    width: 540px;
  }

  .carousel-control-move {
    border: none;
    opacity: 0;
  }

  .carousel-control-move:hover {
    color: #000;
    font-size: 30px;
    border: none;
  }

  .ms5-l-tit {
    font-size: 26px;
    width: 1110px;
    color: #333;
    left: 54px;
    top: 52px;
    font-weight: bold;
    font-family: 'Noto Sans KR', 'NanumBarunGothic', '맑은 고딕', 'Malgun Gothic', sans-serif;
  }

  .image {
    width: 180px;
    height: 254px;
  }
</style>
{% endblock %}

{% block content %}
<br>
<br>

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="4"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="5"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="https://tickets.interpark.com/goods/22011461" target="_blank">
        <img src="https://url.kr/a95hob" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
    <div class="carousel-item" style="width: 1120px">
      <a href="http://ticket.yes24.com/Perf/43185?Gcode=009_303" target="_blank">
        <img src="https://t-img1.wemep.co.kr/wmp-tbanner/43/202209/15/ldy7ytkyxijvtj_pc.jpg" class="d-block w-100"
          alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
    <div class="carousel-item">
      <a href="https://ticket.wemakeprice.com/product/3000007677" target="_blank">
        <img src="https://t-img1.wemep.co.kr/wmp-tbanner/00/202205/15/7kfhksomf6rsck_pc.jpg" class="d-block w-100"
          alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
    <div class="carousel-item">
      <a href="http://ticket.yes24.com/Perf/43061" target="_blank">
        <img src="https://t-img1.wemep.co.kr/wmp-tbanner/07/202209/07/lkgrh1bbatkoen_pc.jpg" class="d-block w-100"
          alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
    <div class="carousel-item">
      <a href="https://ticket.wemakeprice.com/product/3000008255" target="_blank">
        <img src="https://t-img1.wemep.co.kr/wmp-tbanner/44/202208/24/ka5opup1xqk2mv_pc.jpg" class="d-block w-100"
          alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
    <div class="carousel-item">
      <a href="http://www.ticketlink.co.kr/product/39577" target="_blank">
        <img src="https://url.kr/1cihqn" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
    </div>
  </div>
  <button class="carousel-control-prev carousel-control-move" type="button" data-target="#carouselExampleCaptions"
    data-slide="prev">
    <i class="fa-solid fa-arrow-left"></i>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next carousel-control-move" type="button" data-target="#carouselExampleCaptions"
    data-slide="next">
    <i class="fa-solid fa-arrow-right"></i>
    <span class="sr-only">Next</span>
  </button>
</div>

<hr style="margin: 20px 0;">
<div>
  <a href="https://tickets.interpark.com/goods/22010748">
  <img src="https://url.kr/acb3mg" alt="..." style="width:100%"></a>
</div>
<hr style="margin: 20px 0;">

<h4>✔ Ticket pick!</h4>
<div class="card-deck">
  <div class="card">
    <a href="https://tickets.interpark.com/goods/P0003174#">
    <img src="https://media.bunjang.co.kr/product/199548694_1_1663437969_w%7Bres%7D.jpg" class="card-img-top" alt="..."></a>
    <div class="card-body">
      <h5 class="card-title">Love in Seoul 2022</h5>
      <p class="card-text">도심 속 삶의 휴식, 씨어터 뮤직 페스티벌 
        〈LOVE IN SEOUL 2022〉<br>
         
        중독성 강한 팝 사운드<br>
        역대급 떼창의 주인공 ‘크리스토퍼(Christopher)’ 단독 공연</p><br>
      <p class="card-text"><small class="text-muted">세종문화회관 대극장<br>22.11.08 ~ 22.11.28</small></p>
    </div>
  </div>
  <div class="card">
    <a href="http://ticket.yes24.com/Perf/42947?Gcode=009_400">
    <img src="http://tkfile.yes24.com/upload2/PerfBlog/202207/20220719/20220719-42947.jpg" class="card-img-top"
      alt="..."></a>
    <div class="card-body">
      <h5 class="card-title">태양의서커스 〈뉴 알레그리아〉</h5>
      <p class="card-text">
        대한민국을 뒤흔들 단 하나의 공연<br>
        태양의서커스 뉴 알레그리아<br>
        그 화려한 귀환<br>
        10월, 드디어 한국 상륙<br><br><br>
      <p class="card-text"><small class="text-muted">잠실종합운동장 내 빅탑<br>2022.10.20 ~ 2023.01.01</small></p>
    </div>
  </div>
  <div class="card">
    <a href="https://ticket.melon.com/performance/index.htm?prodId=207338">
    <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220922/20220922-43614.jpg" class="card-img-top"
      alt="..."></a>
    <div class="card-body">
      <h5 class="card-title">프랑코 폰타나：컬러 인 라이프</h5>
      <p class="card-text">이번 전시는 작가의 60년대부터 현재까지 고찰하는 예술적 주제이자, 철학이 담겨있는 122점의 작품으로 전개됩니다.
        50년이 넘는 시간 동안 렌즈라는 매개로 담아온 놀라운 삶의 형태와 색채를 직접 확인해 보는 시간이 되셨으면 좋겠습니다.</p>
      <p class="card-text"><small class="text-muted">마이아트뮤지엄<br>2022.09.30 - 2023.03.01</small></p>
    </div>
  </div>

</div>

<hr style="margin: 20px 0;">
<div class="card-group">
  <div class="card-open">
    <div class="card-header">티켓오픈소식</div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">그레이트 서울 인베이전 전국투어 콘서트 - 전주 티켓오픈 안내</li>
      <li class="list-group-item">2022 폴킴 전국투어 콘서트 〈STAR〉 - 춘천 티켓오픈 안내</li>
      <li class="list-group-item">뮤지컬 <브로드웨이 42번가> 1차 티켓오픈 안내</li>
      <li class="list-group-item">뮤지컬 삼총사 마지막 티켓오픈 안내</li>
      <li class="list-group-item">2022 현대카드 다빈치모텔 예약권 티켓오픈 안내</li>
    </ul>
  </div>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <div class="card-open1">
    <div class="card-header">WEEKLY RANKING</div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">1. 잭 화이트 내한공연（Jack White Live in Seoul</li>
      <li class="list-group-item">2. 뮤지컬 [에곤 실레]</li>
      <li class="list-group-item">3. 뮤지컬 [모딜리아니]</li>
      <li class="list-group-item">4. [지정석] 2022 창원 K-POP WORLD FESTIVAL</li>
      <li class="list-group-item">5. 뮤지컬 [시데레우스]</li>
    </ul>
  </div>
</div>

<hr style="margin: 20px 0;">
<p class="ms5-l-tit">📢 REVIEW</p>
<div class="review-group">
  <div class="row">
    <div class="card mb-3 col-6">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img
            src="https://cdnticket.melon.co.kr/resource/image/upload/product/2022/08/2022081115003052ef3ded-81f4-450b-8a60-3e0444da6d9f.jpg/melon/resize/180x254/strip/true/quality/90/optimize"
            class="image" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="card-title">레전드 그 자체!!</h4>
            <p class="card-text">성량 쩔고 청량하고 딕션 짱짱한 라이브 외에도 이미 알려진 바와 같이 거의 한강 불꽃놀이 축제 스케일 + 드론쇼(진짜 개쩔어써)+ 열기구 + 공중공연 등으로
              너무나 꽉꽉 찬 콘서트야
              1부 2부 3부 끝날 때마다 아니 벌써 끝? 했는데 앵앵콜 끝나고 10시 넘은거 보면서 흡입력 엄청난 공연인거 다시 한번 실감했어</p>
            <p class="card-text"><small class="text-muted">2022년 9월 17일(토) 19:00 공연</small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3 col-6">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="https://ticketimage.interpark.com/Play/image/large/22/22010438_p.gif" class="image" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="card-title">밴드는 역시 라이브!</h4>
            <p class="card-text">2시간 내내 쿨타임도 없이 미친듯이 노래 부르며 즐겼다. 또 응원법을 따로 준비해가는 공연과는 달리 멤버가 노래를 부르지 않는 타이밍이나, 코러스 같은 부분을 자연스레 부르게 되는 분위기가 너무 좋았다. 바이올린, 드럼, 베이스, 기타 각각의 소리에 집중하다 보면 이게 밴드의 맛인가 싶었다. 그리고 이 모든 것들의 조화가 너무 아름다웠고 꿈만 같았다.</p>
            <p class="card-text"><small class="text-muted">2022년 9월 3일(토) 19:00 공연</small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3 col-6">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="https://ticketimage.interpark.com/Play/image/large/22/22007866_p.gif" class="image" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="card-title">만족과 실망이 동시에</h4>
            <p class="card-text">빌리아일리시 기대했고, 충분히 그 기대에 만족할만한 공연이었다. 하지만 문제는 공연시간.. 8시15분에 시작해 9시 30분이 조금 넘은시간에 끝나니.. 다소 허탈하다. 가뜩이나 예정시간 95분도 짧다고 느꼈는데 80분남짓에 끝나버리니.. 현카 슈콘 지금까지 다만족했는데 이번에는 실망과 아쉬움도 공존한다.</p>
            <p class="card-text"><small class="text-muted">2022년 8월 15일(월) 20:00 공연</small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3 col-6">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="http://tkfile.yes24.com/upload2/PerfBlog/202207/20220722/20220722-42948.jpg" class="image"
            alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="card-title">광야체험</h4>
            <p class="card-text">드디어 기다리고 기다리던 5년 만의 슴콘 사실 슴콘은 처음이다. 콘서트도 처음이라 후유증이 아직도 남아있는 것같다,,ㅠㅠ </p>
            <p class="card-text"><small class="text-muted">2022년 8월 20일(토) 18:00 공연</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
  <div class="text-white font-italic text-right mr-5">Copyright &copy; 2022 DjangoBook by J.Y</div>
</footer>
{% endblock %}