ticket page/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('',views.PostLV.as_view(),name='index'),
    
    # Example: /blog/post/ (same as /blog/)
    path('post/',views.PostLV.as_view(),name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/',views.PostAV.as_view(),name='post_archive'),
    
    # Example: /blog/archive/2022/
    path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
    
    # Example: /blog/archive/2022/sep/
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month_archive'),

    # Example: /blog/archive/2022/sep/16/
    path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(),name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),
    
    # tag cloud 페이지 추가
    path('tag/',views.TagCloudLV.as_view(),name='tag_cloud'),
    
    # tagged object list 추가
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/',views.SearchFormView.as_view(), name='search'),
    
    path('add/',views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

ticket page/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('',views.BookmarkLV.as_view(),name='index'),
    path('<int:pk>/',views.BookmarkDV.as_view(),name='detail'),
    
    path('add/',views.BookmarkCreateView.as_view(),name='add'),
    path('change/',views.BookmarkChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.BookmarkUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.BookmarkDeleteView.as_view(),name='delete'),
]

ticket page/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',views.HomeView.as_view(),name='home'),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
    path('musical/',include('musical.urls')),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register',views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done',views.UserCreateDoneTV.as_view(), name='register_done'),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ticket page/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE',max_length=100,
                             blank=True)
    url = models.URLField('URL',unique=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.title

ticket page/bookmark/views.py
from django.shortcuts import render
from django.views.generic import *
from bookmark.models import Bookmark
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark
    
class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'
    
    def get_queryset(self):
        return Bookmark.objects.filter(owner = self.request.user)
    
class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')
    
class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

ticket page/bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Change List Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Bookmark Change - {{ user }}</h1>
    <br>

    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Delete Confirm Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        <p>"{{ object }}"를 진짜 삭제하시겠습니까? 이 작업은 돌이킬 수 없습니다. </p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}티켓 오픈 소식 상세{% endblock %}

{% block content %}
<br>
<br>
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
{% endblock %}

ticket page/bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Form Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<br>
<br>
    <h1>Bookmark Create/Update - {{ user }}</h1>
    <p class="font-italic">북마크를 생성하거나 수정을 할 수 있습니다.</p>
    
    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}
    
    <form method="post" class="card pt-3"> {% csrf_token %}
    
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>
    
        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>
    
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

ticket page/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html"%}

{% block title %}티켓 오픈 소식{% endblock %}


{% block extra-style %}
<style>
    .mr-3{
        width:64px;
        height:64px;
    }
    a{
      color:#716DF2;
    }
    a:hover{
      color:#46658C;
    }
</style>
{% endblock %}

{% block content %}
<br>
<br>
    <h1>💡 티켓 오픈 소식</h1>
    <br>
    <!--
    {% if user.is_active %}
        <a class='btn btn-outline-dark' href="{% url 'bookmark:add' %}">글쓰기</a>
        <a class='btn btn-outline-dark' href="{% url 'bookmark:add' %}">내 글 보기</a>
    {% endif %} -->
    <br>
    <!--<ul>
        {% for bm in object_list %}
        <li>
            <a href="{% url 'bookmark:detail' bm.id %}">{{ bm }}</a>
        </li>
        {% endfor %}
    </ul>-->
    <ul class="list-unstyled">
        <li class="media">
          <img src="http://ticketimage.interpark.com/Play/image/large/22/22013168_p.gif" class="mr-3" alt="...">
          <div class="media-body">
            <a href="https://vo.la/mQ06OM">
            <h5 class="mt-0 mb-1">검정치마 - TEEN TROUBLES In Dirty Jersey 티켓오픈 안내</h5></a>
            <h6>티켓오픈일 2022년 9월 29일(목) 오후 7시</h6>
          </div>
        </li>
        <hr>
        <li class="media my-4">
          <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220928/20220928-43663.jpg" class="mr-3" alt="...">
          <div class="media-body">
            <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12210">
            <h5 class="mt-0 mb-1">거미 20주년 전국투어 콘서트〈BE ORIGIN〉- 부산 티켓오픈안내</h5></a>
            <h6>티켓오픈일 2022 9월 28일(수) 오후 2시</h6>          
        </div>
        </li>
        <hr>
        <li class="media">
          <img src="http://ticketimage.interpark.com/Play/image/large/22/22011593_p.gif" class="mr-3" alt="...">
          <div class="media-body">
            <a href="https://vo.la/aJnihV">
            <h5 class="mt-0 mb-1">2022 하이라이트 팬콘 [하이라이트 운동회] 티켓오픈 안내</h5></a>
            <h6>티켓오픈일 2022 9월 28일(수) 오후 7시</h6>          </div>
        </li>
        <hr>
        <li class="media">
            <img src="http://ticketimage.interpark.com/TicketImage/notice_poster/20/2022092617312064.jpg" class="mr-3" alt="...">
            <div class="media-body">
              <a href="https://vo.la/Iumq7T">
              <h5 class="mt-0 mb-1">히사이시 조 영화음악 콘서트 2022_고양 파이널 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022년 10월 5일(수) 오후 2시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://ticketimage.interpark.com/Play/image/large/22/22013006_p.gif" class="mr-3" alt="...">
            <div class="media-body">
              <a href="https://vo.la/wUFfXO">
              <h5 class="mt-0 mb-1">몬스타엑스（MONSTA X）공식팬클럽 ‘MONBEBE’ 7기 추가모집 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022년 9월 28일(수) 오전 10시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="https://cdnticket.melon.co.kr/resource/image/upload/ticketopen/2022/09/202209231636505dadd19f-7362-4db5-a68d-ddc9f8e4bde2.jpg/melon/resize/130x184/strip/true" class="mr-3" alt="...">
            <div class="media-body">
              <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12201">
              <h5 class="mt-0 mb-1">뮤지컬 〈엘리자벳〉 10주년 기념공연－부산 티켓 오픈 안내</h5></a>
              <h6>티켓오픈일 2022년 9월 30일 (금) 오후 2시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220922/20220922-43590.jpg" class="mr-3" alt="...">
            <div class="media-body">
              <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12198">
              <h5 class="mt-0 mb-1">〈러브레터〉 예술의전당 자유소극장 2차 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022 9월 29일(목) 오후 1시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220926/20220926-43630.jpg" class="mr-3" alt="...">
            <div class="media-body">
              <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12200">
              <h5 class="mt-0 mb-1">NCT 127 2ND TOUR ‘NEO CITY : SEOUL - THE LINK +’ 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022 10월 4일(화) 오후 8시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220922/20220922-43611.jpg" class="mr-3" alt="...">
            <div class="media-body">
              <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12176">
              <h5 class="mt-0 mb-1">김고은 데뷔 10주년 팬미팅〈고은날: come in closer〉티켓오픈안내</h5></a>
              <h6>티켓오픈일 2022 9월 22일(목) 오후 2시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://tkfile.yes24.com/upload2/PerfBlog/202209/20220921/20220921-43609.jpg" class="mr-3" alt="...">
            <div class="media-body">
              <a href="http://ticket.yes24.com/New/Notice/NoticeMain.aspx#id=12165">
              <h5 class="mt-0 mb-1">EXID FAN-CON〈EXID X LEGGO〉티켓 오픈 안내</h5></a>
              <h6>티켓오픈일 2022 9월 22일(목) 오후 7시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://ticketimage.interpark.com/Play/image/large/22/22009235_p.gif" class="mr-3" alt="...">
            <div class="media-body">
              <a href="https://vo.la/WQcM3O">
              <h5 class="mt-0 mb-1">뮤지컬 〈라흐 헤스트〉 마지막 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022년 10월 5일(수) 오후 2시</h6> 
            </div>
          </li>
          <hr>
          <li class="media">
            <img src="http://ticketimage.interpark.com/Play/image/large/22/22012976_p.gif" class="mr-3" alt="...">
            <div class="media-body">
              <a href="https://vo.la/FoBA4k">
              <h5 class="mt-0 mb-1">2022 정승환의 안녕, 겨울 : 그럼에도 사랑하게 될 날들 티켓오픈 안내</h5></a>
              <h6>티켓오픈일 2022년 10월 4일(화) 오후 8시</h6> 
            </div>
          </li>
      </ul>
      <br>
{% endblock %}